apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-mongodb
  template:
    metadata:
      labels:
        app: eshop-mongodb
    spec:
      containers:
        - name: eshop-mongodb
          image: mongo
          ports:
            - containerPort: 27017
              name: mongodb
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: eshop-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-services-configuration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-services-configuration
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: eshop-services-configuration
    spec:
      containers:
        - name: eshop-services-configuration
          image: vishipayyallore/eshop-services-configuration:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: CDNHOST
              valueFrom:
                secretKeyRef:
                  name: configuration-values
                  key: CDNHOST
                  optional: false
            - name: APIHOST
              valueFrom:
                secretKeyRef:
                  name: configuration-values
                  key: APIHOST
                  optional: false
            - name: IDENTITY_AUTHORITY
              valueFrom:
                secretKeyRef:
                  name: configuration-values
                  key: IDENTITY_AUTHORITY
                  optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-services-configuration
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: eshop-services-configuration
---
apiVersion: v1
kind: Secret
metadata:
  name: configuration-values
data:
  CDNHOST: ZHVtbXktY2Ru
  APIHOST: ZHVtbXktYXBp
  IDENTITY_AUTHORITY: aHR0cDovL2xvY2FsaG9zdDo1MDAx